### ISSUE TITLE
How to bulid search book form

### ISSUE THREAD

**Issue by iamtol** [mdn/express-locallibrary-tutorial#50] opened 2018-08-22 03:01 UTC
i want to continue for search form in local library, how to implement ?

**Comment by hamishwillee** [comment] 2018-08-27 01:13
Actually building a form and integrating it into the existing forms would be easy, and you can infer from the existing documentation. 

We also show how to search various fields in the mongodb as part of documentation, and also for finding matching records.

So while I do not know exactly how to do this, I do believe the tools to do it have already been provided to you.

I'm closing, as supporting this in "detail" is beyond the scope of the tutorial - and not a bug.

**Closed by hamishwillee** 2018-08-27 01:13 UTC
