### ISSUE TITLE
Heroku not setting database to production

### ISSUE THREAD

**Issue by plee61** [mdn/express-locallibrary-tutorial#79] opened 2019-11-12 02:35 UTC
On the [deployment article](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment), I followed the steps to change database config from development to production but Heroku is still pointing to the development database. I have also verified MONGO databases, new data record is still being added to development database. Everything else works.
Please help.
Cheers

**Comment by hamishwillee** [comment] 2019-11-12 02:49
Did you set the MONGODB_URI  environment variable?

**Comment by plee61** [comment] 2019-11-12 03:19
Yes, I followed everything there
> heroku config:set MONGODB_URI=

**Comment by plee61** [comment] 2019-11-15 02:51
I have checked the dash board on Heroku, the "conf vars" is set correctly pointing MONGODB_URI to production. But the website on Heroku is still pointing to development

**Comment by hamishwillee** [comment] 2019-11-15 02:56
I'm sorry, I do not have time to try debug this for you. Where I would be looking is your code that uses the MONGODB_URI - ie a typo or similar so setting the URI makes no difference.

**Comment by hamishwillee** [comment] 2020-10-16 05:44
Hi
I have tested the instructions in the [deploying article](https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment) "from scratch" and they work. 

If you can see that your MONGODB_URI is set correctly then most likely you missed the step where you set that this is the URI that is used - ie see https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment#Database_configuration 

So what you would check is that in app.js your database is set like this:
```
var mongoDB = process.env.MONGODB_URI || dev_db_url;
```
That should fix the problem, but if not then the next thing is to check whether this variable is what is being passed to connect.

Closing as cannot reproduce.

**Closed by hamishwillee** 2020-10-16 05:44 UTC
