### ISSUE TITLE
error on heroku deployment, ..models/bookinstance not found

### ISSUE THREAD

**Issue by MadRiver44** [mdn/express-locallibrary-tutorial#27] opened 2017-12-12 18:08 UTC
**I am having a successful build,  yet when I enter heroku open, the deployment fails.  Here is the push to heroku master...**

Counting objects: 59, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (59/59), done.
Writing objects: 100% (59/59), 23.12 KiB | 0 bytes/s, done.
Total 59 (delta 42), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote: 
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote: 
remote: -----> Installing binaries
remote:        engines.node (package.json):  8.9.3
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Resolving node version 8.9.3...
remote:        Downloading and installing node 8.9.3...
remote:        Using default npm version: 5.5.1
remote: 
remote: -----> Restoring cache
remote:        Loading 2 from cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (not cached - skipping)
remote: 
remote: -----> Building dependencies
remote:        Installing node modules (package.json + package-lock)
remote:        added 73 packages, removed 106 packages and updated 13 packages in 5.203s
remote: 
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 2 cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (nothing to cache)
remote: 
remote: -----> Build succeeded!
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> web
remote: 
remote: -----> Compressing...
remote:        Done: 21.3M
remote: -----> Launching...
remote:        Released v6
remote:        https://calm-everglades-12109.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/calm-everglades-12109.git
da1f479..9c81077  master -> master

**Here are the heroku logs from command line [https://gist.github.com/MadRiver44/853fa6a27379c43a0ae5debd841787f7](url)**

**Why is it not finding the ..models/bookinstance?**
**The steps I've taken  are: check and compare code, check package.json, looked for typos, check all requires, all models and controllers, and tested locally ---which works fine, and read heroku troubleshooting node.js apps**

**Comment by hamishwillee** [comment] 2017-12-12 22:20
Is this the using the source code from here (unmodified?). 
Does it work for you if you run it locally?

**Comment by MadRiver44** [comment] 2017-12-13 01:28
yes, unmodified. It runs fine locally.

**Comment by hamishwillee** [comment] 2017-12-13 02:20
Can you repeat on a new dyno. Sometimes the upload screws up.

**Comment by MadRiver44** [comment] 2017-12-13 13:21
i'll try and report back

**Comment by MadRiver44** [comment] 2017-12-13 19:03
Nope, the restart didn't work. I git cloned the source repo, ran fin locally and on heroku. I then compared mine to yours for typos, changes in the controllers and models, line by line, no errors.

**Comment by hamishwillee** [comment] 2017-12-13 21:46
That is very odd. I started a fresh clone and it all worked fine following the instructions in the tutorial. See:
```
git clone https://github.com/mdn/express-locallibrary-tutorial.git
cd express-locallibrary-tutorial
heroku create
D:\Github\MDNUPDATE\test\express-locallibrary-tutorial>heroku create
Creating app... done, infinite-journey-93901
https://infinite-journey-93901.herokuapp.com/ | https://git.heroku.com/infinite-journey-93901.git

D:\Github\MDNUPDATE\test\express-locallibrary-tutorial>git push heroku master
Counting objects: 219, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (105/105), done.
Writing objects: 100% (219/219), 106.82 KiB | 0 bytes/s, done.
Total 219 (delta 112), reused 219 (delta 112)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  8.9.1
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 8.9.1...
remote:        Downloading and installing node 8.9.1...
remote:        Using default npm version: 5.5.1
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (not-found)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (package.json + package-lock)
remote:        added 175 packages in 4.982s
remote:
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 2 cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (nothing to cache)
remote:
remote: -----> Build succeeded!
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> web
remote:
remote: -----> Compressing...
remote:        Done: 21.3M
remote: -----> Launching...
remote:        Released v3
remote:        https://infinite-journey-93901.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/infinite-journey-93901.git
 * [new branch]      master -> master

D:\Github\MDNUPDATE\test\express-locallibrary-tutorial>heroku open
```
If that precise process does not work, can you please create your own repository (of the build that fails) and I can try that.

**Comment by MadRiver44** [comment] 2017-12-15 15:33
Sure, here is my [repo of my code](https://github.com/MadRiver44/LibraryApp)

**Comment by hamishwillee** [comment] 2017-12-20 07:13
OK, so the problem is that your code attempts to load **models/bookinstance.js** but the file is actually named with a captial "I" - **models/bookInstance.js**. 

When I fixed this as shown below everything worked:
```
git mv models/bookInstance.js models/bookinstance.js
```
I worked this out using the logging command: `heroku logs --tail` (see debug below).
As this is not a bug in the example or the docs, and the mechanism I used to debug this [is in the docs here](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment#Debugging) I am closing this issue.

As an aside, that is a very easy mistake to make (I did similar, which is how I discovered the logging and debugging commands). Hope this helps you in future :-)

### Debug log below ....

```
D:\Github\MDNUPDATE\test\kevin\LibraryApp>heroku logs --tail
2017-12-20T06:57:19.071220+00:00 app[api]: Initial release by user hamishwillee@gmail.com
2017-12-20T06:57:19.071220+00:00 app[api]: Release v1 created by user hamishwillee@gmail.com
2017-12-20T06:57:19.153709+00:00 app[api]: Release v2 created by user hamishwillee@gmail.com
2017-12-20T06:57:19.153709+00:00 app[api]: Enable Logplex by user hamishwillee@gmail.com
2017-12-20T06:57:50.000000+00:00 app[api]: Build started by user hamishwillee@gmail.com
2017-12-20T06:58:04.031226+00:00 app[api]: Release v3 created by user hamishwillee@gmail.com
2017-12-20T06:58:04.031226+00:00 app[api]: Deploy b3dc54e3 by user hamishwillee@gmail.com
2017-12-20T06:58:04.052162+00:00 app[api]: Scaled to web@1:Free by user hamishwillee@gmail.com
2017-12-20T06:57:50.000000+00:00 app[api]: Build succeeded
2017-12-20T06:58:07.330322+00:00 heroku[web.1]: Starting process with command `npm start`
2017-12-20T06:58:10.805584+00:00 app[web.1]:
2017-12-20T06:58:10.805699+00:00 app[web.1]: > library@0.0.0 start /app
2017-12-20T06:58:10.805700+00:00 app[web.1]: > node ./bin/www
2017-12-20T06:58:10.805701+00:00 app[web.1]:
2017-12-20T06:58:11.741296+00:00 app[web.1]: module.js:538
2017-12-20T06:58:11.741311+00:00 app[web.1]:     throw err;
2017-12-20T06:58:11.741312+00:00 app[web.1]:     ^
2017-12-20T06:58:11.741312+00:00 app[web.1]:
2017-12-20T06:58:11.741314+00:00 app[web.1]: Error: Cannot find module '../models/bookinstance'
2017-12-20T06:58:11.741315+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:536:15)
2017-12-20T06:58:11.741316+00:00 app[web.1]:     at Function.Module._load (module.js:466:25)
2017-12-20T06:58:11.741317+00:00 app[web.1]:     at Module.require (module.js:579:17)
2017-12-20T06:58:11.741317+00:00 app[web.1]:     at require (internal/module.js:11:18)
2017-12-20T06:58:11.741319+00:00 app[web.1]:     at Object.<anonymous> (/app/controllers/bookController.js:5:20)
2017-12-20T06:58:11.741319+00:00 app[web.1]:     at Module._compile (module.js:635:30)
2017-12-20T06:58:11.741320+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:646:10)
2017-12-20T06:58:11.741320+00:00 app[web.1]:     at Module.load (module.js:554:32)
2017-12-20T06:58:11.741321+00:00 app[web.1]:     at tryModuleLoad (module.js:497:12)
2017-12-20T06:58:11.741322+00:00 app[web.1]:     at Function.Module._load (module.js:489:3)
2017-12-20T06:58:11.741322+00:00 app[web.1]:     at Module.require (module.js:579:17)
2017-12-20T06:58:11.741323+00:00 app[web.1]:     at require (internal/module.js:11:18)
2017-12-20T06:58:11.741323+00:00 app[web.1]:     at Object.<anonymous> (/app/routes/catalog.js:5:23)
2017-12-20T06:58:11.741324+00:00 app[web.1]:     at Module._compile (module.js:635:30)
2017-12-20T06:58:11.741325+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:646:10)
2017-12-20T06:58:11.741325+00:00 app[web.1]:     at Module.load (module.js:554:32)
2017-12-20T06:58:11.752181+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-12-20T06:58:11.752944+00:00 app[web.1]: npm ERR! errno 1
```

**Closed by hamishwillee** 2017-12-20 07:13 UTC
