### ISSUE TITLE
Book Instance functionality not working as expected. 

### ISSUE THREAD

**Issue by rosskinney** [mdn/express-locallibrary-tutorial#86] opened 2019-12-31 21:18 UTC
Hello, 

I am having two issues with the Book Instance functionality.  I don't know if issue 1 is related to issue 2. 

1. After clicking on the All-book-instances link, the page renders as expected, but none of the books are clickable. 

2.  When trying to add a new book instance, an error is thrown with the following message: 

I have gone through the tutorial several times and I think the controller and views have been set-up correctly

Cast to ObjectId failed for value "undefined" at path "_id" for model "BookInstance"
CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "BookInstance"
    at new CastError (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/error/cast.js:39:11)
    at ObjectId.cast (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/schema/objectid.js:246:11)
    at ObjectId.SchemaType.applySetters (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/schematype.js:975:12)
    at ObjectId.SchemaType._castForQuery (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/schematype.js:1389:15)
    at ObjectId.SchemaType.castForQuery (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/schematype.js:1379:15)
    at ObjectId.SchemaType.castForQueryWrapper (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/schematype.js:1358:15)
    at cast (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/cast.js:315:32)
    at model.Query.Query.cast (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/query.js:4698:12)
    at model.Query.Query._castConditions (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/query.js:1876:10)
    at model.Query.<anonymous> (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/query.js:2131:8)
    at model.Query._wrappedThunk [as _findOne] (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at /Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/kareem/index.js:369:33
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

Please let me know if I can provide additional documentation for this issue. 

Thanks in advance for any assistance you can provide.

**Comment by hamishwillee** [comment] 2020-01-05 22:15
Hi Ross,
Does this specific library work for you - ie the code in this repo? Are you using your own database for this, or the one online?

**Comment by rosskinney** [comment] 2020-01-06 23:42
Hi, 
I have not tried the code in the repo.  I am using my own database which I seeded using the instructions in the tutorial.  

Thanks!

**Comment by hamishwillee** [comment] 2020-01-06 23:49
Can you please try the code in this repo with your environment and database. If it fails, that indicates an environment issue. If it succeeds it indicates the environment is OK and there is something wrong with your code. 

The error means that it doesn't know the type of object that the ID is. Probably something silly in the routes definition. Hard to be sure - JavaScript sux. Can you post a repo of your current code?

**Comment by rosskinney** [comment] 2020-01-07 00:05
Sure.  It wouldn't surprise me if it is a routes issue.  

Thanks so much for the suggestions.  

https://github.com/rosskinney/locallibrary

**Comment by hamishwillee** [comment] 2020-01-07 23:13
Thanks. Unfortunately I have no idea when I will be able to look at this closer. I'd start by differencing this example.

**Comment by Ontheroad123** [comment] 2020-06-06 03:02
> Hello,
> 
> I am having two issues with the Book Instance functionality. I don't know if issue 1 is related to issue 2.
> 
>     1. After clicking on the All-book-instances link, the page renders as expected, but none of the books are clickable.
> 
>     2. When trying to add a new book instance, an error is thrown with the following message:
> 
> 
> I have gone through the tutorial several times and I think the controller and views have been set-up correctly
> 
> Cast to ObjectId failed for value "undefined" at path "_id" for model "BookInstance"
> CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "BookInstance"
> at new CastError (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/error/cast.js:39:11)
> at ObjectId.cast (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/schema/objectid.js:246:11)
> at ObjectId.SchemaType.applySetters (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/schematype.js:975:12)
> at ObjectId.SchemaType._castForQuery (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/schematype.js:1389:15)
> at ObjectId.SchemaType.castForQuery (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/schematype.js:1379:15)
> at ObjectId.SchemaType.castForQueryWrapper (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/schematype.js:1358:15)
> at cast (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/cast.js:315:32)
> at model.Query.Query.cast (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/query.js:4698:12)
> at model.Query.Query._castConditions (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/query.js:1876:10)
> at model.Query. (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/query.js:2131:8)
> at model.Query._wrappedThunk [as _findOne] (/Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
> at /Users/rosskinney/node-js/express-locallibrary-tutorial/node_modules/kareem/index.js:369:33
> at processTicksAndRejections (internal/process/task_queues.js:75:11)
> 
> Please let me know if I can provide additional documentation for this issue.
> 
> Thanks in advance for any assistance you can provide.

when i create bookinstance,there is some errors, and i see my database not have bookinstance table,you can find you database,make sure there are datas in bookinstance.

**Comment by hamishwillee** [comment] 2020-06-08 01:58
The first test is to see whether this example works. If it does, then it is your code that is the problem, so you can start by differencing your code and this code.

**Comment by hamishwillee** [comment] 2020-10-12 05:52
Closing - cannot reproduce(works on this repo)

@rosskinney I am assuming you have either resolved the issue or moved on to something else. I am therefore closing this. If you still need help and are interested in further investigation, let me know and I can look further.

**Closed by hamishwillee** 2020-10-12 05:52 UTC
